environment:
  - tdp/production
config:
  tdp-platform:clusterStackRef: chiply-org/tdp-cluster/production
  tdp-platform:resourceTier: standard
  tdp-platform:prometheusRetention: "30d"
  tdp-platform:prometheusScrapeInterval: "15s"
  tdp-platform:prometheusStorageSize: "50Gi"
